---
title: "Econometria espacial com R - Aula 04"
author: "Raphael Saldanha, Eduardo Almeida"
subtitle: Unicamp, julho de 2017
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

# Regressão ponderada geograficamente

## Pacote

```{r}
library(spgwr)
```

## Shapefile

```{r}
# Pacotes
library(rgdal)

brmicro.shp <- readOGR("data", "br_micro", encoding = "ISO-8859-1")

# Plotar o mapa
plot(brmicro.shp)
```

## Dados

```{r}
dados <- read.csv2("data/Dados_GWR.csv", header = TRUE)
str(dados)
```

## Especificação

```{r}
esp <-  Q9303 ~ P9303 + G0 + CI9303
```


## Modelo OLS

```{r}
mod1 <- lm(formula = esp, data = dados)
summary(mod1)
```

## Verificando erros do modelo

```{r}
plot(mod1, which=3)
```

## Verificando resíduos no espaço

```{r}
resids<-residuals(mod1)
cores <- c("dark blue", "blue", "red", "dark red") 
map.resids <- SpatialPointsDataFrame(data=data.frame(resids), coords=cbind(dados$X_COORD,dados$Y_COORD)) 
spplot(map.resids, cuts=quantile(resids), col.regions=cores, cex=1) 
```

## Kernel bandwith

```{r}
GWRbandwidth <- gwr.sel(esp, data=dados, coords = cbind(dados$X_COORD,dados$Y_COORD), adapt = TRUE) 
```

## Modelo GWR

```{r}
mod1.gwr = gwr(esp, data=dados, coords = cbind(dados$X_COORD,dados$Y_COORD), adapt=GWRbandwidth, hatmatrix=TRUE, se.fit=TRUE) 
mod1.gwr
```

